// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCGDQ9djQ2MC3DalhvfZmmS9QEKuISB85Y',
    appId: '1:615969496854:web:401feb27bb53cab02f7a37',
    messagingSenderId: '615969496854',
    projectId: 'chaat-appp-fb096',
    authDomain: 'chaat-appp-fb096.firebaseapp.com',
    storageBucket: 'chaat-appp-fb096.appspot.com',
    measurementId: 'G-NMTC7YNPD1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAxuNfWCfl4qgZbtXTimanIZVl6Mz2SfBg',
    appId: '1:615969496854:android:98d871417dae96b02f7a37',
    messagingSenderId: '615969496854',
    projectId: 'chaat-appp-fb096',
    storageBucket: 'chaat-appp-fb096.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDlPA5Hd9EZNipQfElHPyE3kG7eKKUVWsA',
    appId: '1:615969496854:ios:137aeac3f203e5222f7a37',
    messagingSenderId: '615969496854',
    projectId: 'chaat-appp-fb096',
    storageBucket: 'chaat-appp-fb096.appspot.com',
    iosBundleId: 'com.example.chaaaaat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDlPA5Hd9EZNipQfElHPyE3kG7eKKUVWsA',
    appId: '1:615969496854:ios:87b7e4b1888f12292f7a37',
    messagingSenderId: '615969496854',
    projectId: 'chaat-appp-fb096',
    storageBucket: 'chaat-appp-fb096.appspot.com',
    iosBundleId: 'com.example.chaaaaat.RunnerTests',
  );
}
